### PR TITLE
Update CODE_OF_CONDUCT.md to 1.1.0

### PR DESCRIPTION
**Pull request by strand**

### CODE REVIEW

**Comment by tpitale** [comment]
It's already v1.1.0 …

**Comment by tpitale** [comment]
https://github.com/growingdevs/growingdevs.github.io/pull/41/files#diff-a1ee87dafebc22cbd96979f1b2b7e837L27

**Comment by strand** [comment]
Whoops, most projects aren't up-to-date. Thanks!

**Comment by tpitale** [comment]
No sweat, thanks for checking!

**Pull request closed without merging**
